env:
  browser: true
  es2021: true
  jest/globals: true
extends:
  - "plugin:react/recommended"
  - standard
  - "plugin:prettier/recommended"
  - "prettier/@typescript-eslint"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
  - jest
  - prettier
rules:
  {
    "no-use-before-define": "off",
    "@typescript-eslint/no-use-before-define": ["error"],
    "prettier/prettier": "error",
    "react/prop-types": "off",
  }
settings:
  react:
    version: detect
