export const PLAY_LIST_ADD = "PLAY_LIST_ADD";
export const PLAY_LIST_UPDATE = "PLAY_LIST_UPDATE";
export const PLAY_LIST_SELECT = "PLAY_LIST_SELECT";
export const PLAY_LIST_DELETE = "PLAY_LIST_DELETE";
